///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsAtmosphere = 'assets/Atmosphere.jpg';
  static const String assetsClear = 'assets/Clear.jpg';
  static const String assetsClouds = 'assets/Clouds.jpg';
  static const String assetsHome = 'assets/home.jpg';
  static const String assetsRain = 'assets/Rain.jpg';
  static const String assetsRainy = 'assets/rainy.jpg';
  static const String assetsRsm = 'assets/rsm.jpg';
  static const String assetsSunny2 = 'assets/sunny2.jpg';
  static const String assetsThunderstorm = 'assets/Thunderstorm.jpg';

}
